const validName = /^[$A-Z_][0-9A-Z_$]*$/i, reserved = {
  'break': true,
  'case': true,
  'catch': true,
  'class': true,
  'const': true,
  'continue': true,
  'debugger': true,
  'default': true,
  'delete': true,
  'do': true,
  'else': true,
  'export': true,
  'extends': true,
  'finally': true,
  'for': true,
  'function': true,
  'if': true,
  'import': true,
  'in': true,
  'instanceof': true,
  'new': true,
  'return': true,
  'super': true,
  'switch': true,
  'this': true,
  'throw': true,
  'try': true,
  'typeof': true,
  'var': true,
  'void': true,
  'while': true,
  'with': true,
  'yield': true,
}

export const isValidFuncName = (s) => validName.test(s) && !reserved[s]
